### ISSUE TITLE
add save_data methods for input dependent parts in Models and Controllers

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/UpAndGo#154]

**Comment by nikitadizhur** [comment]
@OmriBS from what I see, we have to write:
- [ ] load/save chosen courses
- [ ] load/save current schedule
- [ ] load/save gilaion
- [ ] load/save catalog

check out those one that you will finish or add smth if you feel needed

**Comment by OmriBS** [comment]
@nikitadizhur , ok.
to prevent any problems (that we will work on the same method i'll take load/save chosen courses and load/save current schedule

**Comment by nikitadizhur** [comment]
@OmriBS sorry, didn't see your comment.
Can you, please, take catalog? because, I have no idea how to use it

**Comment by OmriBS** [comment]
@nikitadizhur , me too but ok, i'll take with sapir.
just to be clear, which methods you implement?

**Comment by nikitadizhur** [comment]
@OmriBS for now schedule
