### ISSUE TITLE
Project interview

### ISSUE THREAD

**Issue by AdiOmari** [TechnionYP5777/UpAndGo#166]
Lidia @Lidkin5 and Alex @alexvitho, 

We would like to interview each of you tomorrow. Please select a time for the interview by writing your name in the following document:
https://docs.google.com/document/d/14eTOc1KL5d0LQEymoZCmf7RuqoBlHJfbmDcnUN8l2lM/edit#

Thanks

**Comment by alexvitho** [comment]
עדי שלום,
יש לנו בעיה להגיע מחר. לידיה עובדת מחר, יש לה פגישות חשובות בעבודה (היא לא יכולה לבטל יום עבודה בהתראה של 12 שעות).
יש לנו הצגת פרוייקט ארדוינו ביום שלישי ומכיוון שהיא מחר בעבודה אני חייב לסיים את המטלות שנישארו (יש לא מעט) . תזמנו בבקשה מישהו אחר אנחנו ניהיה זמינים אחרי ההצגה ביום שלישי. 
@AdiOmari

**Comment by Lidkin5** [comment]
@AdiOmari 
היי , אולי בבקשה תחליפו אותנו עם זוג אחר ? 
זה ממש בעייתי .

**Comment by AdiOmari** [comment]
@alexvitho @Lidkin5 
We do short interviews and do them during the course lecture hours in order not to have such excuses. The two free slots left are the last two (starting 17:50), alex can start and then lidia at (18:10). 20 minutes is not a lot of time, so we don't think it will affect your work on the arduino project. 

If you still insist it is problematic (going to work when short in time in your study says otherwise), then we will try to find a different slot.

**Comment by Lidkin5** [comment]
done.

**Comment by alexvitho** [comment]
@AdiOmari  
איפה הפגישה?

**Comment by alexvitho** [comment]
SSDLחדר סמינרים לייד ה
