### ISSUE TITLE
Decide Which Web Framework We Will Use

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#171]
After some research, I've narrowed down the options into three candidates:

**Play Framework**: from the official website https://www.playframework.com/ - "Play is a high-productivity **Java** and Scala web application framework that **integrates the components** and APIs you need for modern web application development.

Play is based on a lightweight, stateless, web-friendly architecture and features predictable and minimal resource consumption (CPU, memory, threads) for highly-scalable applications thanks to its reactive model, based on Akka Streams." 

**Spring Framework**: from the official website https://projects.spring.io/spring-framework/ - "The Spring Framework provides a comprehensive programming and configuration model for modern **Java-based** enterprise applications - on any kind of deployment platform. A key element of Spring is infrastructural support at the application level: Spring focuses on the "plumbing" of enterprise applications so that teams can focus on application-level business logic, without unnecessary ties to specific deployment environments."

**GWT**: from the official website http://www.gwtproject.org/overview.html - "GWT is a development toolkit for building and optimizing complex browser-based applications. Its goal is to enable productive development of high-performance web applications without the developer having to be an expert in browser quirks, XMLHttpRequest, and JavaScript. GWT is used by many products at Google, including AdWords, AdSense, Flights, Hotel Finder, Offers, Wallet, Blogger. It’s open source, completely free, and used by thousands of developers around the world." 
Reasons why we should use GWT:
http://stackoverflow.com/questions/13714018/spring-gwt-or-spring-vs-gwt
http://stackoverflow.com/questions/8455435/jquery-vs-google-closure-va-gwt-pros-cons-for-large-web-application-developmen/8458169#8458169

eastimated time: 2-3 hours

**Comment by nikitadizhur** [comment]
@danabra, from what I have read, Play needs some code in Scala, so I don't think it will suite our goals.
From one hand GWT is much easier to learn and is more suitable for small applications, but from the another it relies on MVP (which is more suitable for desktop like web application as I see now) and not on MVC model. Maybe we can change the model, though, or try to incorporate GWT with Spring and thus minimize the usage of the last.
Maybe it will really be better to switch to MVP, but it will demand some work to do.

**Comment by danabra** [comment]
@nikitadizhur Where did you read that? because I'm pretty sure you don't need any scala code - There are two different API's one for java and one for scala, so we'll use only the java API.

**Comment by nikitadizhur** [comment]
@danabra 
http://stackoverflow.com/questions/17743671/do-you-need-to-know-scala-to-play-around-with-java-play-framework
https://zeroturnaround.com/rebellabs/the-curious-coders-java-web-frameworks-comparison-spring-mvc-grails-vaadin-gwt-wicket-play-struts-and-jsf/       (e.g. pages 3 and 4)

**Comment by danabra** [comment]
@nikitadizhur Well it does not say that you have to **code** in scala, but either way we can still use spring.

**Comment by nikitadizhur** [comment]
@danabra okay. I would even consider switch to MVP and Sencha GXT, as it is more suitable for our type of application, but you decide.

**Comment by danabra** [comment]
@nikitadizhur I suggest that we'll discuss this in our upcoming meeting.

**Comment by kobybs** [comment]
according to Sencha website it is not free, check it out and let me know.
also, GWT & going MVP should be an option too.

**Comment by danabra** [comment]
@kobybs Yes, it does seems to be not free.
@nikitadizhur After further reading, I have come to the conclusion that GWT is probably the most suitable option for our application, though, like you said, we will need to switch to MVP - and I think we should.
http://stackoverflow.com/questions/13714018/spring-gwt-or-spring-vs-gwt
http://stackoverflow.com/questions/8455435/jquery-vs-google-closure-va-gwt-pros-cons-for-large-web-application-developmen/8458169#8458169

**Comment by kobybs** [comment]
great. I think it's the best option too.

**Comment by yossigil** [comment]
👍

**Comment by nikitadizhur** [comment]
we decided on MVP with GWT.
