### ISSUE TITLE
Study The Chosen Framework

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#172]
We will have to study the new framework before we can start using it.
estimated time: 10-15 hours

**Comment by nikitadizhur** [comment]
Task:
create textbox with "apply" button. when you press apply it show the written text as entry to table.

each one of the team has to check in the checkbox and add the screenshot of performed task in the comment below.

- [ ] **Nikita**.
- [ ] **Koby**.
- [ ] **Dan**.
- [ ] **Omri**.
- [ ] **Yaniv**.

**Comment by leyaniv** [comment]
Please share any tips and insights [here](https://github.com/TechnionYP5777/UpAndGo/wiki/Some-GWT-insights)

**Comment by nikitadizhur** [comment]
done.
