### ISSUE TITLE
Transfer Old Code to Web Framework

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#173]
Some of the back-end code will be reused from the old code.

estimated time: 40 hours

**Comment by nikitadizhur** [comment]
create branch with old code and erase unused code from the master branch (in particular view and controller).
@OmriBS, you have to change installation instruction in accordance to new branch.

**Comment by danabra** [comment]
@OmriBS Inorder to reach the old project's code you will have to run this in the command line:
``git checkout old_project``
and inorder to return to the current code run:
``git checkout master``
If you are having any difficulties then let me know.

**Comment by nikitadizhur** [comment]
see #207
