### ISSUE TITLE
Study Gmail API for authentication

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#175]
we can start here: https://developers.google.com/gmail/api/auth/about-auth

time estimation: 5 hours

**Comment by leyaniv** [comment]
I'm not sure that GMail API is the same as Google API.
I think we should add the Google API Sign-In as written here: https://developers.google.com/identity/sign-in/web/

**Comment by yossigil** [comment]
Check if there is no java lib that simplifies the mail authentication
