### ISSUE TITLE
Add Hardcoded Constraints On Schedule

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#193]
e.g for times that I can't have lectures.

time estimation: 6 hours

**Comment by kobybs** [comment]
this one has 2 seperate parts:
1) changing the backend to support Hardcoded constraints.
2) changing the gui in a way the user can click on the table and sets a hardcoded constraint that way.
and should be two different issues. 
I can estimate the backend part to be 4 hours. 
the gui part can't be done before studying our new platform.

**Comment by nikitadizhur** [comment]
see #202, #203
