### ISSUE TITLE
write presentation

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/UpAndGo#210]
write presentation

**Comment by OmriBS** [comment]
great!
i can't open the link that you shared in your comment...
anyway, my email is omri.benshmuel@gmail.com.
I plan to also work on the presentation today so when we meet tomorrow we can focus on writing the presentor part
@nikitadizhur

**Comment by nikitadizhur** [comment]
@OmriBS I have sent you a sharing request

**Comment by OmriBS** [comment]
@nikitadizhur , got it. Looks very professional.

**Comment by nikitadizhur** [comment]
estimation time 6h.

**Comment by nikitadizhur** [comment]
waiting for the dry run

**Comment by tanyabrokhman** [comment]
Can i see?
tanya.linder@gmail.com

**Comment by nikitadizhur** [comment]
@tanyabrokhman shared document with you

**Comment by nikitadizhur** [comment]
done
