### ISSUE TITLE
rename main package from "presenter" to "upandgo"

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/UpAndGo#218]

**Comment by kobybs** [comment]
@leyaniv IT'S A BLOCKER!! do it ASAP. the whole architecture of the project is wrong. 
@nikitadizhur *it's not nice to have*. presenter is a subpackage of the project, along with view and model, being the top package is not the way it should be.

**Comment by leyaniv** [comment]
@kobybs sorry I wan't available for a day

**Comment by nikitadizhur** [comment]
@leyaniv. I have already renamed package to "webapp", so I'll close the issue now.
