### ISSUE TITLE
CourseListPresenter and CourseListView refactoring

### ISSUE THREAD

**Issue by leyaniv** [TechnionYP5777/UpAndGo#228]

**Comment by danabra** [comment]
@nikitadizhur Don't forget to add course search functionality

**Comment by nikitadizhur** [comment]
add KeyUpHandler (for course searching) and CellPreviewHandler (for double-click, hover) and delete all other handlers

**Comment by nikitadizhur** [comment]
@danabra, I changed presenter in accordance with what we discussed today.

**Comment by nikitadizhur** [comment]
done
