### ISSUE TITLE
Transfer server-side logic to client side

### ISSUE THREAD

**Issue by kobybs** [TechnionYP5777/UpAndGo#230]
in the TimeTableGUI.java file there are some computation which probably can't be done in the client side like using LocalTime and etc. we need to design a solution in which most of the calculation of how the table should look like will be done over server side. and only after that the drawing proccess will be done using the data calculated by the server.

let me know.

**Comment by nikitadizhur** [comment]
@kobybs, can't we just change LocalTime to Date (of java.util)? it may be a little uglier, than with LocalTime, but if it can work on the client side, then why not?
