### ISSUE TITLE
Get Hovered Course Row

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#231]

**Comment by danabra** [comment]
@nikitadizhur I found a way to do that, Basically I get the height of each list item, h, and then I return (Y_coord / h). If you find a better way then let me know, or you can close the issue.

**Comment by nikitadizhur** [comment]
@danabra, I think we can use CellList class to solve this:
[http://stackoverflow.com/questions/7818222/mouse-over-event-on-the-column-of-a-gwt-celltable](url)

**Comment by danabra** [comment]
@nikitadizhur Yes, CellTable looks like the right choice.
