### ISSUE TITLE
Add Tooltip Plugin and Implement Course Tooltip

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#241]

**Comment by danabra** [comment]
I used [this plugin](https://github.com/ArcBees/gwtquery-tooltip-plugin) for the tooltips of courses. Hre are some [examples](http://arcbees.github.io/gwtquery-tooltip-plugin/) to what can be done with this plugin (exactly what we need!)

**Comment by danabra** [comment]
@nikitadizhur I've added two function to the Display interface - setHoveredRow and setHoveredCourseDetail - so please implement them.
setHoveredCourseDetail - sets the hovered course name detail (using mousemovehandler)
setHoveredRow - need to be called only when setHoveredCourseDetail is called.

**Comment by nikitadizhur** [comment]
done
