### ISSUE TITLE
refactor CourseId to use Calendar

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/UpAndGo#264]

**Comment by danabra** [comment]
@OmriBS read this: https://stackoverflow.com/questions/7009655/how-to-use-java-util-calendar-in-gwt

**Comment by OmriBS** [comment]
@danabra , Calendar is not supported by GWT and it seems that joda is not supported by app-engine (not included in java 7) so both libraries will create problems for us...
maybe we need to return to our own implement and forget the advanced features that we wanted- like show the weekends between exams or show the day of the exam (i can still give you the amount of days between exams), what do you say?

**Comment by danabra** [comment]
@OmriBS Use Calendar only in the server side, and send to the client side strings that represent dates
