### ISSUE TITLE
moving save schedule button to NavBar

### ISSUE THREAD

**Issue by OmriBS** [TechnionYP5777/UpAndGo#293]

**Comment by leyaniv** [comment]
can someone remind me why we decided to do it?
there's enough place for buttons now that they are on the left side of the screen
@OmriBS

**Comment by OmriBS** [comment]
@leyaniv , maybe it's not relevant anymore. we just wanted to save some space

**Comment by leyaniv** [comment]
@OmriBS we don't care about users with low resolution screens!
