### ISSUE TITLE
Bugs found by visitors

### ISSUE THREAD

**Issue by kobybs** [TechnionYP5777/UpAndGo#322]
- Can't find the Remove button, since it's too far away from course title.
- After setting a course lecture as a constraint and than removing that course and selecting him again - the constraint still applies, is it what we expect? (removed by the collisions window, maybe behaves differently when removed by the 'Remove all' or 'Remove' button)
- פילאטיס 23  - doesn't show ! but scheduler does found it good at Wednesday.
- change the pale third color to something darker

you may add more bugs to the list.

**Comment by leyaniv** [comment]
accidently closed by last comit

**Comment by danabra** [comment]
see a3e957c66ab8e8c444296a7cedc1d4cdb8c5ffbb
