### ISSUE TITLE
Time choosing doesn't work on the first hour of the day

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/UpAndGo#335]
Created by Shahar.
When trying to add an event on the first hour of Sunday, for example, the time frame option does'nt work.
![image](https://user-images.githubusercontent.com/23077804/27768810-df9b79e4-5f24-11e7-881a-6f1d44e146d8.png)

**Comment by kobybs** [comment]
This bug probably caused because we spartanized the project. 
we now reverted it back to NORMAL code, please try again and close if solved.

**Comment by Shahar-Y** [comment]
You were right. All is good now. 
Closing.
