### ISSUE TITLE
Can't create a new event right after an old one 

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/UpAndGo#337]
The timeframe next to a "built-in" class is not clickable.
in the example below, Monday, 10:30 is not clickable.
![image](https://user-images.githubusercontent.com/23077804/27768882-020e337a-5f27-11e7-9016-e01e6d5be275.png)

**Comment by kobybs** [comment]
This bug probably caused because we spartanized the project. 
we now reverted it back to NORMAL code, please try again and close if solved.

**Comment by Shahar-Y** [comment]
You were right. All is good now, thank you!
Closing issue.
