### ISSUE TITLE
[Final] Showing null before sign in

### ISSUE THREAD

**Issue by tomerdragucki** [TechnionYP5777/UpAndGo#338]
When pressing Sign in button, the following appears for a second before I'm transferred to the google account window:
<img width="205" alt="screen shot 2017-07-02 at 13 14 24" src="https://user-images.githubusercontent.com/23155308/27768971-d3c60ad6-5f28-11e7-8b08-5ffd8dcb5de9.png">

**Comment by nikitadizhur** [comment]
@tomerdragucki, thank you for report. can't fix it right now. will be fixed later

**Comment by tomerdragucki** [comment]
In addition, I think that it happens only when I'm not logged in to any google account but after pressing Sign in this appears:
<img width="1278" alt="screen shot 2017-07-02 at 13 21 03" src="https://user-images.githubusercontent.com/23155308/27769151-4ce5d146-5f2c-11e7-8ab4-46210bb76727.png">
and then this:
<img width="1280" alt="screen shot 2017-07-02 at 13 21 15" src="https://user-images.githubusercontent.com/23155308/27769152-55c30356-5f2c-11e7-92d4-3ecba837afc2.png">
and then I'm transferred to this page:
<img width="961" alt="screen shot 2017-07-02 at 13 21 53" src="https://user-images.githubusercontent.com/23155308/27769158-628c7266-5f2c-11e7-955f-1f108bea59ce.png">

**Comment by nikitadizhur** [comment]
@tomerdragucki, yes it was temporary problem, because we deployed new version. now it should be fine

**Comment by tomerdragucki** [comment]
I reopened the site and it still appears

**Comment by nikitadizhur** [comment]
@tomerdragucki, strange, I can't recreate this behavior. Can you check again now, please? or give more details on what you did exactly?

**Comment by tomerdragucki** [comment]
I'm not logged in to any google account on my browser, and just press sign in, and then the windows I took screenshot of appear

**Comment by nikitadizhur** [comment]
@tomerdragucki what is your browser?
as a suggestion, you can use Firefox. It should work

**Comment by nikitadizhur** [comment]
@tomerdragucki, I think both of the problems you mentioned are now solved, so I will close the issue.
feel free to reopen it if you think otherwise.
