### ISSUE TITLE
Bug in a collision between a course and an user event

### ISSUE THREAD

**Issue by osherh** [TechnionYP5777/UpAndGo#339]
When a course and an Event collides the system tells me to give up user event 999999 - unclear which event you meant

![screenshot from 2017-07-02 13-14-34](https://user-images.githubusercontent.com/15803467/27768974-dc021852-5f28-11e7-81e2-894cd12bc3dd.png)

**Comment by kobybs** [comment]
We meant for the user event which created by the user :
![image](https://user-images.githubusercontent.com/22766102/27768997-5faa6588-5f29-11e7-84d3-e0ef1afce4ec.png)
we gave those events the number 999999, but it is weird and probably shouldn't be presented. thanks.

**Comment by kobybs** [comment]
fixed please check it out and let us know.

**Comment by osherh** [comment]
works!
