### ISSUE TITLE
A visual "jump" when pointing with mouse on course list

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/UpAndGo#341]
Hi, (using chrome browser)
When I put מבני בטון2 in the course list next to the bottom of the list, and I hover the mouse from the right or left of the screen onto the name of the course, the pop-up text that explains the details of the course over-flows beyond the bottom of the screen, causing a scrolling bar on the right of the screen to show up, and gives a "jump" on the page. This same scroll bar disappears as soon as I hover the mouse away from this particular course. (of course, this will happen with any course that has a large text box for the course details that is near the bottom of the list).

**Comment by danabra** [comment]
fixed

**Comment by TomPalny** [comment]
Good job!
