### ISSUE TITLE
The details box of a course shows up unpredictably

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/UpAndGo#342]
Hi,
When I hover with the mouse over the name of a course in the course list, the course details text box sometimes shows up and sometimes not when the mouse moves around. For example, in the following picture my mouse was over the course (you can't see this in the printScreen) and the text box disappeared, in other occasions, in the same place where my mouse was on, the text box appeared. 
![image](https://user-images.githubusercontent.com/15875450/27769105-6413e3cc-5f2b-11e7-9c3f-48995ce33884.png)

**Comment by danabra** [comment]
yes it is a known bug.
