### ISSUE TITLE
The exam list after clicking "לוח מבחנים"

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/UpAndGo#345]
The list after clicking לוח מבחנים could be done without the need to scroll sideways, something which on a laptop or a computer is not very intuitive.
In other words, if you can somehow visually place all the exams in the same perspective, by creating a smaller rectangle around the exam, and by squeezing several consecutive free days with a "-" (meaning using a dash to show range of number of days) you can eliminate the need to scroll at all.
If you want a quick fix, just show a sideways scrollbar to indicate that there is a sideways scrolling option (right now there isn't any such scrollbar)

**Comment by TomPalny** [comment]
Another quickfix, is to place a > arrow button in the right and left sides of the exam list that will be click and holdable to scroll to the sides of the list. (the scrollbar is an ugly thing, it's best not to show it, as you did now, and the arrow buttons will serve as enough visual indication that there is "more info on the right/left")

**Comment by danabra** [comment]
Thats a great idea, but we won't be able to implement it in the duration of the reality test
