### ISSUE TITLE
יצוא מערכת is not clear how to allow

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/UpAndGo#346]
When I click "יצוא מערכת", it shows the comment as shown below. 
It is not clear how to allow google to do it. Please add more instructions or a link of some sort.
![image](https://user-images.githubusercontent.com/23077804/27769206-c125a562-5f2d-11e7-950b-08a37a637801.png)

**Comment by nikitadizhur** [comment]
@Shahar-Y aren't you redirected to the page where you set permissions?

**Comment by nikitadizhur** [comment]
@Shahar-Y, I think message is clearer now, so I will close the issue.
feel free to reopen it if you think otherwise.
