### ISSUE TITLE
[Final] The details box of a course is confused sometimes

### ISSUE THREAD

**Issue by tomerdragucki** [TechnionYP5777/UpAndGo#347]
Sometimes the details box stays even though I'm not over the course and as you can see below, two details boxes appear to me.
<img width="571" alt="screen shot 2017-07-02 at 13 55 25" src="https://user-images.githubusercontent.com/23155308/27769225-24917a36-5f2e-11e7-9e15-89ff3f8e290d.png">

**Comment by kobybs** [comment]
@danabra

**Comment by danabra** [comment]
@tomerdragucki  It is a known bug, to fixed this simply click anywhere outside the popup.
