### ISSUE TITLE
בנה מערכת Shows weired choosing option

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/UpAndGo#349]
It asks me to remove on of the following courses, but only one course is shown.
The מערכת I chose is shown in the image below.
![image](https://user-images.githubusercontent.com/23077804/27769244-a3497982-5f2e-11e7-94f9-9c78b29720f7.png)

**Comment by danabra** [comment]
@Shahar-Y you mean that it shoud have been "וותר על הקורס" instead of "וותר על אחד מהקורסים"?
