### ISSUE TITLE
[Final] Free days constraint not working (?)

### ISSUE THREAD

**Issue by tomerdragucki** [TechnionYP5777/UpAndGo#351]
I'm not sure but after I tick Sunday for example:
<img width="595" alt="screen shot 2017-07-02 at 14 08 08" src="https://user-images.githubusercontent.com/23155308/27769322-ec82335e-5f2f-11e7-8bdb-767bedc1c7e2.png">
and save it, I press on "בנה מערכת" but still get lessons schedule for Sunday:
<img width="1271" alt="screen shot 2017-07-02 at 14 09 22" src="https://user-images.githubusercontent.com/23155308/27769334-15f559be-5f30-11e7-9fc9-ce9f83979477.png">

**Comment by OmriBS** [comment]
the scheduler work as "best effort", if your constraint is not possible, the system will ignore it.
because 234312 have a lecture on sunday and no other option the system ignore your request of free day on monday

**Comment by tomerdragucki** [comment]
Thanks! maybe you can add a dialog telling there's no option for the current constraints like you do in course collisions.
