### ISSUE TITLE
Not enough info in collison

### ISSUE THREAD

**Issue by osherh** [TechnionYP5777/UpAndGo#353]
not giving the user enough info on suggestions to courses to give up on in case of collision

**Comment by osherh** [comment]
![bug](https://user-images.githubusercontent.com/15803467/27769432-a52bde4a-5f31-11e7-9e70-a1d83ffb6ada.png)

**Comment by kobybs** [comment]
scheduling problem is an NP problem. it's cannot be done both efficiently and comprehensivly.
therefore we support only schedules which can be resolved by removing at most 1 colliding course.
the error message above means that all possible schedules has at least 2 colliding courses. In that case finding the exact courses who causes the problem will demand extremly heavy calculations. so we just ask the user to remove an arbitrary course and try again.
