### ISSUE TITLE
Course info hint displays info of wrong course

### ISSUE THREAD

**Issue by Amit-Oha** [TechnionYP5777/UpAndGo#356]
![screenshot from 2017-07-03 13-21-20](https://user-images.githubusercontent.com/1254412/27788769-975c9b9e-5ff2-11e7-8887-b7070fbb6702.png)
On the first time I just searched for 234 and then the wrong info showed up. On the second time I succeeded to recreate this bug by showing info for a certain course (in this case statistics), then moving the mouse and searching for another course and then hovering over the new appeared course - the old hint still showed up. If I move the mouse again and then return it, the correct info shows up.

**Comment by Amit-Oha** [comment]
It appears that the issue is deeper - now it shows the wrong course for every course in the box. Not sure how this happens.

**Comment by danabra** [comment]
It has to do with the server handling a lot of requests, it will be fixed
