### ISSUE TITLE
Same schedule appears a few times with different groups

### ISSUE THREAD

**Issue by Amit-Oha** [TechnionYP5777/UpAndGo#357]
For this bug I chose only two courses - 014006 and 014113.
Up&Go generated 6 schedules, when there are actually two groups of 3 same schedules.
This is because it generates a schedule for each recitation group, which is understandable, but ultimately when considering schedules it doesn't matter as long as they are happening in the same time.

**Comment by OmriBS** [comment]
from the program point view it is not a bug, some courses have the same lesson hours but with different staff so it is still a valid different schedule.

**Comment by OmriBS** [comment]
for example,
![image](https://user-images.githubusercontent.com/23152420/27790514-700cbcc0-5ff9-11e7-8363-2ef5f7a094c1.png)<br>
![image](https://user-images.githubusercontent.com/23152420/27790530-7ddd1642-5ff9-11e7-994e-0eb548482d78.png)

**Comment by Amit-Oha** [comment]
As I said, I understand this is intended, but as a schedule creator I don't think it is correct logically. Moreover the tab is too small to display the different recitation groups, so even if you disagree with my opinion it is not clear to the user what is the difference between the schedules.

**Comment by nikitadizhur** [comment]
Thank you for your opinion, we will consider it.
