### ISSUE TITLE
Karma and Todos for Alex V.

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/UpAndGo#4]
_From @alexvitho on October 28, 2016 18:30_

#330
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#573_

**Comment by zvili** [comment]
_From @alexvitho on October 28, 2016 18:31_

@yossigil  Done.

**Comment by zvili** [comment]
_From @Lidkin5 on October 28, 2016 18:55_

Great karma page  👍 
check mine :)

**Comment by zvili** [comment]
_From @yossigil on October 28, 2016 20:31_

:-1: full name please

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 2:14_

Add a "quality assurance" and "teaching" labels to this issue. Add a deadline.

**Comment by zvili** [comment]
_From @alexvitho on October 29, 2016 16:11_

@yossigil 
I have a problem with putting my full - first and last name on public website (even on Facebook). 
Can i please keep the first capital letter of my last name ?

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 18:29_

OK

**Comment by Lidkin5** [comment]
this is the link to the telegram group:

https://telegram.me/joinchat/EVRXNgtDloAU6YmGsfmeHQ
