### ISSUE TITLE
Wiki article: links to project that we based on them

### ISSUE THREAD

**Issue by SapirBismot** [TechnionYP5777/UpAndGo#52]
- TTime code
- Udonkey code

**Comment by OmriBS** [comment]
@SapirBismot  @kobybs @alexvitho  @Lidkin5 @nikitadizhur @leyaniv 
the projects can be found in the wiki section of the project.

UDonkey - course scheduling program that receives list of courses and builds a schedule while considering number of variables (relevant to koby task). written in c#
TTime - more upgraded version based on UDonkey. written in ruby.

both projects can't be executed but they are open source and well documented and may save alot of time.
