### ISSUE TITLE
Add prerequisites tree of the courses

### ISSUE THREAD

**Issue by SapirBismot** [TechnionYP5777/UpAndGo#53]
maybe use Boris code.

**Comment by SapirBismot** [comment]
I'm not sure about the linked courses/ (קורס צמוד):
For example: 234122 (Matam) and 234118 (Atam).
We can register atam before matam or both together but can not register matam before atam.

**Comment by yossigil** [comment]
LINKED MEANS: co-requisite

**Comment by nikitadizhur** [comment]
irrelevant
