### ISSUE TITLE
Implement Schedule 

### ISSUE THREAD

**Issue by danabra** [TechnionYP5777/UpAndGo#69]
Implement Schedule class.
Depends on Timetable implementation and Constraint implementation

**Comment by kobybs** [comment]
@danabramovich Schedule should be a class holding a list of LessonGroup and a list of TimeConstraints.
also, implement a function(maybe even static) that given a schedule, tells if its a valid one.
this function need to verify:
1. every lesson group can meet the constaints. e.g : there is no lesson between 2 p.m to 4 p.m on thusday. 
2. the lesson groups doesn't clash between themselves. 
make sure you use and understand TimeConstraint, and WeekTime.
