### ISSUE TITLE
refactor Model

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/UpAndGo#76]
- [x] rename Model to CourseModel and make it concrete
- [x] add method loadQuery to load need courses (by name/subname) from DB
- [x] create interface Model
- [x] delete ConcreteModel and use CourseModel instead

**Comment by nikitadizhur** [comment]
1st and 3rd are done

**Comment by yossigil** [comment]
Use markdown checkboxes

- [ ] One

- [ ] Two
