### ISSUE TITLE
create an example XML file 

### ISSUE THREAD

**Issue by kobybs** [TechnionYP5777/UpAndGo#77]
which will have the same structure of the file created by deep parsing ( #54 ).
should have at least 2-3 courses. 

this is a blocker of sprint 1.1 so should be closed as soon as possible.

**Comment by leyaniv** [comment]
I created a template here
https://github.com/TechnionYP5777/UpAndGo/wiki/Courses-XML-Template
This is how I think it should look like, but lets discuss it before creating an example file.

**Comment by OmriBS** [comment]
in Course class we have 'faculty' field but in yaniv's template the faculty of the course isn't mentioned...
@leyaniv @kobybs

**Comment by OmriBS** [comment]
@leyaniv , in the dates of exams can you please insert the full year i.e "2016" instead of "16"
and time format of HH:mm instead of 9:00.
we need it for the LocalDateTime type which uses "yyyy-MM-dd HH:mm" format

**Comment by leyaniv** [comment]
@OmriBS 
no problem, i'll do it tonight

**Comment by OmriBS** [comment]
@leyaniv, the format is missing a reference to the Prerequisites or Corequisites of the course.
and missing additional data regarding the staff (email, office, office hours- i don't know if this data can be found in the REP file, if not, we need to change StaffMember class)

**Comment by leyaniv** [comment]
@OmriBS 
just want to point out that manually adding "20" before a given year (so "16" will be presented as "2016") will create a "y2k1h bug" in our project :boom:

**Comment by OmriBS** [comment]
@leyaniv, you've got a point... think of it as a possible loop-hole after the program will transfroms itself to Skynet and ensalve all of humanity... the machines will send back in time a robot that will disguise itself as ATUDAI to infiltrate our project and fix the bug

**Comment by leyaniv** [comment]
can we close this? @OmriBS ?

**Comment by OmriBS** [comment]
@leyaniv ,i think so.. 
can you please post the template after the changes that you have made? (adding faculty, padding zeros and etc..) to make sure that we are on the same page.
and can you create example of courses of type project and laboratory?

**Comment by yossigil** [comment]
@OmriBS : what's this strange avartar? @zvili

**Comment by yossigil** [comment]
@leyaniv יהושוע -> יהושע

**Comment by OmriBS** [comment]
@yossigil it's just a random git cat i've found on google..
i don't have any pictures on my facebook/whatsApp/gmail/telegram profiles... is it really crucial here?

**Comment by yossigil** [comment]
Can you find something more unique please? We will be in trouble if everyone uses such anonymous avatars. 
![image](https://cloud.githubusercontent.com/assets/12775400/21596147/d2a65aa6-d13f-11e6-8f74-0c1f284b1d5a.png)

**Comment by kobybs** [comment]
@leyaniv  this is not relevant anymore, checkout your issue stack and close issues that are already done, or no longer need to be done.
