### ISSUE TITLE
making market survey on potential users' preferences

### ISSUE THREAD

**Issue by OmriBS** [TechnionYP5777/UpAndGo#81]
@leyaniv @nikitadizhur @Lidkin5 @alexvitho @kobybs @SapirBismot 
i would like to read your opinion on this subject.
maybe it will be good for the project if we'll compose online survey and distribute it among the other students and ask them what features they seek in a project like ours.
this can provides fresh ideas for our scheduler and make us more user-oriented (and of course that we don't have to do everything that they will want).
the survey will adress only the scheduler part and not the course's suggestions part.
i've composed first draft of such survey, tell me what you think- what to add/remove or what to change.
https://docs.google.com/forms/d/e/1FAIpQLSeC07MX77uUG01k2nWcLMPhx2JRxxl4gwZkG9JVDUetBu_pUg/viewform

**Comment by kobybs** [comment]
I think it's a great idea. the draft too.

**Comment by yossigil** [comment]
Amazing idea @OmriBS: it is best if you recruit real customers, perhaps now and perhaps for next semester.

**Comment by OmriBS** [comment]
you can find the results of the survey in the Wiki tab under "Customers survey results"
