### ISSUE TITLE
add loadAllCourses() and loadCoursesWithSubname(String name) to loader?

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/UpAndGo#86]
I want to add the above two methods to loader for easier communication.
both of them return list of Course.

**Comment by nikitadizhur** [comment]
@leyaniv @kobybs what do you think about it?

**Comment by leyaniv** [comment]
loadallcourses can be useful.
what the other one does? what's a subname?

**Comment by nikitadizhur** [comment]
@leyaniv if you type "234" instead of full course number, you will receive all courses that have "234" inside their numbers

**Comment by leyaniv** [comment]
oh ok, please consider calling it loadCoursesByPartialID.

**Comment by nikitadizhur** [comment]
ok

**Comment by yossigil** [comment]
Why copy UG? Why not search course, where you can put either course ID (partial) or a word from title.
Don't copy this design error from UG

**Comment by nikitadizhur** [comment]
find a workaround for it in #95 and #96, so doesn't really need those methods now.
done
